name: Setup Poetry
description: Installs and sets up Poetry
inputs:
  python-version:
    description: "Python version for caching"
    required: true
  poetry-version:
    description: "Poetry version to install"
    required: false
    default: "1.1.13"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python - -y --version=${{ inputs.poetry-version }}
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Restore Poetry venv from cache
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}

    - name: Create Poetry venv with dependencies
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install